name: Sync README to vortexa-docs

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sdk repository
        uses: actions/checkout@v2

      - name: Checkout vortexa-docs repository
        uses: actions/checkout@v2
        with:
          repository: 'vortexa-labs/vortexa-docs'
          token: ${{ secrets.GH_TOKEN }}
          path: 'vortexa-docs'

      - name: Copy README.md to vortexa-docs
        run: |
          cp README.md vortexa-docs/packages/sdk/README.md

      - name: Commit and push if changed
        working-directory: ./vortexa-docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/sdk/README.md
          git commit -m "Update README from sdk repository" || exit 0
          git push
